# Generated by Django 5.1.1 on 2024-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('solution', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SpellingBee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('words', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('word', models.CharField(max_length=5)),
            ],
        ),
    ]
