# Generated by Django 5.1.1 on 2024-09-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haterade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('endpoint', models.CharField(max_length=1)),
            ],
        ),
    ]
